const dashboard = <i className="fa-solid fa-chart-line"></i>
const transactions = <i className="fa-solid fa-credit-card"></i>
const categories = <i className="fa-solid fa-tags"></i>
const accounts = <i className="fa-solid fa-wallet"></i>
const settings = <i className="fa-solid fa-cog"></i>
const logout = <i className="fa-solid fa-sign-out"></i>
const trend = <i className="fa-solid fa-money-bill-trend-up"></i>
const expenses = <i className="fa-solid fa-money-bill-transfer"></i>
const money = <i className="fa-solid fa-money-bill"></i>
const freelance = <i class="fa-solid fa-house-laptop"></i>
const stocks = <i className="fa-solid fa-arrow-trend-up"></i>
const bitcoin = <i className="fa-brands fa-bitcoin"></i>
const piggy = <i className="fa-solid fa-piggy-bank"></i>
const card = <i className="fa-brands fa-cc-visa"></i>
const users = <i className="fa-solid fa-users-between-lines"></i>
const rupee = <i class="fa-solid fa-indian-rupee-sign"></i>
const calender = <i className="fa-solid fa-calendar"></i>
const comment = <i className="fa-solid fa-comment"></i>
const plus = <i className="fa-solid fa-plus"></i>
const trash = <i className="fa-solid fa-trash"></i>
const signout = <i className="fa-solid fa-right-from-bracket"></i>
const takeaway = <i className="fa-solid fa-utensils"></i>
const clothing = <i className="fa-solid fa-shirt"></i>
const book = <i className="fa-solid fa-book-open"></i>
const food = <i className="fa-solid fa-bowl-food"></i>
const medical = <i className="fa-solid fa-briefcase-medical"></i>
const tv = <i className="fa-solid fa-tv"></i>
const circle = <i className="fa-solid fa-circle-dot"></i>
const groceries = <i class="fa-solid fa-cart-shopping"></i>
const travelling = <i class="fa-solid fa-plane"></i>

export { accounts, bitcoin, book, calender, card, categories, circle, clothing, comment, dashboard, expenses, food, freelance, logout, medical, money, piggy, plus, rupee, settings, signout, stocks, takeaway, transactions, trash, trend, tv, users, groceries, travelling }